# Development mode docker-compose. This create additional volumes for changing source files reclects on containers
# Running:
#     docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

version: "3"

services:
  api_rest:
    volumes:
      - ./API_REST:/app

  worker_vad:
    volumes:
      - ./worker_vad:/app

  worker_low_level_features:
    volumes:
      - ./worker_low_level_features:/app

  audio_extractor:
    volumes:
      - ./audio_extractor:/app

  asr_worker:
    volumes:
      - ./worker_asr:/app

  aggregator_worker:
    volumes:
      - ./aggregator:/app

  topic_segmentation_worker:
    volumes:
      - ./temp/word2vec:/word2vec
      - ./topic_segmentation_algorithm:/app
